### ISSUE TITLE
Only 1 file being used ?

### ISSUE THREAD

**Issue by dhirensr** [WeizmannVision/ssfmri2im#1]
Hello @RomaBeliy  ,
I noticed in the config file only https://github.com/WeizmannVision/ssfmri2im/blob/e4d5b75f0f60f8f1c0e6d41e050e6327f21577a8/config_file.py#L13 Subject3.mat is being used.However there are 5 mats available? 
is this project extendable if I want to train encoder with all 5 mat files?

**Comment by RomaBeliy** [comment]
Hello @dhirensr,
Each mat file contains the information about a different subject.
The aim of this project is to obtain a model for a single subject, a multi subject model is outside the scope of this project.
I believe that there are a number of possible ways to extend this projects to multiple subjects, it really depends on your goals, some of the extension are simple but others are highly non-trivial.

**Comment by dhirensr** [comment]
@RomaBeliy : thanks for the reply.
I just wanted to ask if I wanted to extend for all 5 subjects then would it be easier to scale?

**Comment by RomaBeliy** [comment]
If you were to concatenate the voxels of the 5 subjects, and reduce the batch size to 32, 32 GB of GPU RAM should suffice. You can probably manage with less GPU RAM if you decreased the batch size more.

**Comment by dhirensr** [comment]
@RomaBeliy : thanks a lot for your reply :smile:
